language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
before_script:
- npm run build
after_script:
- npm run test
deploy:
  provider: npm
  email: klausmachado@gmail.com
  api_key:
    secure: JoliHsiLMpDpYbae0Ahvhj7qcmVps0C426r9Bh7s3KemGBV09o34EgVbDfPNyNAKJswoXhKvtZdWxS2X5KDeLtzyfoNSnZ46/43Pun5+GAXDOaIFLy4AKdmP1tTzwhKaoCjhbPMML8SCk23hP3BrB+vJLIuZlMft9EkIubPpwgwjoYeadF+8lYXeBWRvvfmhgIqdc8dey/JEe+NOTH5+YgBWv5uu8FmBlXP5YwKJXNZ6RhvqEAamm7EDJTIFAggL556AUc+l+n40ZTZiKxH8nNvRakWvky0StZinHLsS6ggIJOW1hdZbuOVHb2T6Xu1L7hb63MF3u9glk1QK8SiO2TlzbKUp4gn1OOgycmZEq2kiEjLR7vfjiy/uuAjVfKX5VmLWIfXlUSpC2X/wKCXk8Zj0QgE6Igck+z+iWmfdmxeFV3S0C8ONSAZbOfqRVvzu+uQ0np1JJTL92aV8ZrpTHIGFc5VGpk5weEVW9nNZqVLWqVIevDAbI9KNbejGUfpkJG24+lYUlc+UjFsCIXLd2AQovgcv3uK39GTxCBd18DQfYZq8hHIAAESPeon3LVFHjjbEpzvA2S2P+/LCuHSAlSGj/ZU6u+5o06Z+Gb3cCpiSzwi45/QAPiokZlXF3LydPGRPQQaB4M5owuwJ6xfdAKOcSaoQUkoDU1DtOiYcDts=
  on:
    tags: true
    repo: klauskpm/evmt
