language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
#before_deploy:
#- yarn global add rollup rollup-plugin-babel rollup-plugin-uglify
before_script:
- npm run build
after_script:
- npm run test
deploy:
  provider: npm
  email: klausmachado@gmail.com
  api_key:
    secure: C+WY2ZMGAspQtBuyjRfQa6j5UKvX2PwUSO+8kdDNserWxaatmMbyI3Cc+AKih7VPy/qYJJBqR0FWOocogCsjsgtthYjZlnE69UuHumG9UI649I4yQ+1xlC3z7+MxO6vqA5Ggq2A6qCOY7TrVoX8ReCzy16TlgodmvMCmfcq1iSe8DKsK1dDjPhFFFLMPRzcJwhuBe8SZm+OqACKo0h3I5dSh3njfWJTZyPcJTot6EhxpyiONdjWW1EWRyARBXnVC8oe11rLw0sCIUynyEX9hJFn+8js3f+h4spk9qnGJOuG+Wjl9M0X9uRAT2y3ch1VJ5daPU5Cf+YNHMcbwtRN9Tb6G0khngshj6rJUpCIYe1/n5p1rJg2//A2xcJq+kYi8ybUcIZsPNDApdGC7amwPPQlyuFmass1kMfZjkXB7NQQLofA57V9KTwr8r0jM8S3Sfb0W3cFSsBKiEGMImtMjtcbX2FrR5ATzMc3pv9q0g5ml4cf2wpi1krhVupQeKqZ+/7SK8xxzflbL/fQimdVGGVzn1vY/YUudo0OgkIU8uiXXh8+HyY/2RY2fsioOFdloKzVABYYiEAobLljfsA1XiFyATqIsAom+mlTPBUD/E6xA1ucS+wpz1ezu6iP5cd8KN+8AGyCNI0/cR9NuynJVa5eg3cFbVj7hX4RZPS3cGpU=
  on:
    tags: true
    repo: klauskpm/evmt
